### ISSUE TITLE
I wonder if Vite will also be added?

### ISSUE THREAD

**Issue by Selnapenek** [s1owjke/js-bundler-benchmark#1]

**Comment by s1owjke** [comment]
Although I originally was thinking of adding it, but when I tried to configure Vite I got a number of difficulties, usually solutions that work well out of the box are more difficult to configure for specific requirements.

Vite uses Rollup and Esbuild under the hood, but because they use their own plugins the results are slightly different, in some cases it's a little bit faster in some cases a little bit slower. 

Here are my early measurements for the Vite, I don't guarantee that they are 100% correct

|                      | Empty | Libraries | Mui   | Synthetic |
| -------------------- | ----- | --------- | ----- | --------- |
| **Rollup: esbuild**  | 1.874 | 5.553     | 5.746 | 14.612    |
| **Vite**             | 2.329 | 6.2731    | 5.273 | 10.704    |
| **Webpack: esbuild** | 0.808 | 3.145     | 2.665 | 8.798     |

**Comment by s1owjke** [comment]
@Selnapenek I have good news for you, I had some time for debugging and now I have [added Vite](https://github.com/s1owjke/js-bundler-benchmark/pull/3) to the benchmark, updated measurements will be coming soon
